create table categories(
                           id int primary key generated by default as identity,
                           name varchar(64) not null unique
);

create table cities(
                       id int primary key generated by default as identity,
                       name varchar(128) not null unique
);

create table if not exists offers
(
    id          bigint primary key,
    title       varchar(64)    not null,
    description varchar(2500)  not null,
    category    varchar(64)    not null,
    currency    varchar(16)    not null,
    price       numeric(19, 2) not null,
    created_at  timestamptz default now(),
    city_id     int            not null references cities(id),
    user_id     bigint not null
);

create sequence if not exists offers_seq
    start with 1
    increment by 50
    cache 50;

create table offer_images(
    id bigint primary key,
    offer_id bigint not null references offers(id),
    image_bucket varchar(255) not null,
    image_path varchar(255) not null,
    created_at timestamptz not null default now()
);

create sequence if not exists offer_images_seq
    start with 1
    increment by 50
    cache 50;

create table if not exists offer_calendar
(
    id          bigint primary key,
    date        date                            not null,
    offer_id    bigint references offers (id)   not null,
    is_booked   boolean  default false not null
);

create sequence if not exists offer_calendar_seq
    start with 1
    increment by 50
    cache 50;

create table rent_request(
    id bigint primary key,
    offer_id bigint references offers(id),
    user_id bigint not null
);

create sequence if not exists rent_request_seq
    start with 1
    increment by 50
    cache 50;

create table if not exists rent_request_dates
(
    rent_request_id bigint not null references rent_request(id),
    offer_date_id   bigint not null references offer_calendar(id),
    primary key (rent_request_id, offer_date_id)
);