server:
  port: 8081
spring:
  application:
    name: auth
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: me
    password: 1234
    url: jdbc:postgresql://localhost:25434/domostroy_auth_db
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
  liquibase:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      acks: all
      properties:
        idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      topics:
        user-registered: user.registered
jwt:
  secret: 731ecd05cfdfa62d6a85516db9ad16aed03e509fea730ab9f5685135fb3e05151254e7598112f72831af367d3b6045b5c3980b70c62aa5177bc80fd01c41eb51
  expiration: 360
  strength: 10

messaging:
  type: kafka
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: me
    password: 1234
    url: jdbc:postgresql://domostroy:5432/domostroy_db
  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
  data:
    redis:
      host: redis
      port: 6379
jwt:
  secret: 731ecd05cfdfa62d6a85516db9ad16aed03e509fea730ab9f5685135fb3e05151254e7598112f72831af367d3b6045b5c3980b70c62aa5177bc80fd01c41eb51
  expiration: 360
  strength: 10



