server:
  port: 8082
spring:
  application:
    name: core
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: me
    password: 1234
    url: jdbc:postgresql://localhost:25431/domostroy_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sleuth:
      sampler:
        probability: 1.0

yandex:
  cloud:
    storage:
      access-key: YCAJE1FHWZkDylXWh-O9h2NkI
      secret-key: YCPADQl1RcXELxxJoQ2GzNZaulsXFb08Ta2hFC_U
      region: "ru-central1"
      endpoint: "https://storage.yandexcloud.net"
      bucket: "domostroy"
jwt:
  secret: 731ecd05cfdfa62d6a85516db9ad16aed03e509fea730ab9f5685135fb3e05151254e7598112f72831af367d3b6045b5c3980b70c62aa5177bc80fd01c41eb51
  expiration: 60
  strength: 10

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: me
    password: 1234
    url: jdbc:postgresql://localhost:25431/domostroy_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sleuth:
      sampler:
        probability: 1.0

yandex:
  cloud:
    storage:
      access-key: YCAJE1FHWZkDylXWh-O9h2NkI
      secret-key: YCPADQl1RcXELxxJoQ2GzNZaulsXFb08Ta2hFC_U
      region: "ru-central1"
      endpoint: "https://storage.yandexcloud.net"
      bucket: "domostroy"
jwt:
  secret: 731ecd05cfdfa62d6a85516db9ad16aed03e509fea730ab9f5685135fb3e05151254e7598112f72831af367d3b6045b5c3980b70c62aa5177bc80fd01c41eb51
  expiration: 60
  strength: 10