server:
  port: 8082
spring:
  application:
    name: core
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: me
    password: 1234
    url: jdbc:postgresql://localhost:25433/domostroy_core_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true

  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
services:
  auth-service:
    url: http://localhost:8081

yandex:
  cloud:
    storage:
      access-key: YCAJE1FHWZkDylXWh-O9h2NkI
      secret-key: YCPADQl1RcXELxxJoQ2GzNZaulsXFb08Ta2hFC_U
      region: "ru-central1"
      endpoint: "https://storage.yandexcloud.net"
      bucket: "domostroy"
jwt:
  secret: 731ecd05cfdfa62d6a85516db9ad16aed03e509fea730ab9f5685135fb3e05151254e7598112f72831af367d3b6045b5c3980b70c62aa5177bc80fd01c41eb51
  expiration: 60
  strength: 10
ai:
  moderation:
    key: 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

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: me
    password: 1234
    url: jdbc:postgresql://domostroy:5432/domostroy_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false

yandex:
  cloud:
    storage:
      access-key: YCAJE1FHWZkDylXWh-O9h2NkI
      secret-key: YCPADQl1RcXELxxJoQ2GzNZaulsXFb08Ta2hFC_U
      region: "ru-central1"
      endpoint: "https://storage.yandexcloud.net"
      bucket: "domostroy"
jwt:
  secret: 731ecd05cfdfa62d6a85516db9ad16aed03e509fea730ab9f5685135fb3e05151254e7598112f72831af367d3b6045b5c3980b70c62aa5177bc80fd01c41eb51
  expiration: 60
  strength: 10

logging:
  level:
    org.springframework.web.multipart: DEBUG
ai:
  moderation:
    key: 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