server:
  port: 8083
spring:
  application:
    name: notifications

---
spring:
  config:
    activate:
      on-profile: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false

---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: alien228133@gmail.com
    password: oedp kcyi tpdd jgou
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
