server:
  port: 8083
spring:
  application:
    name: notifications

---
spring:
  config:
    activate:
      on-profile: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: domostroy.noreply@gmail.com
    password: vnca hatf qqav zywu
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topics:
        user-registered: user.registered
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: user-events
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    listener:
      ack-mode: batch
messaging:
  type: kafka

---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: domostroy.noreply@gmail.com
    password: vnca hatf qqav zywu
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
